version: 2
project_name: "gh-web-auth"
builds:
  -
    id: "gh-web-auth"
    binary: "gh-web-auth"
    env:
      - "CGO_ENABLED=0"
    goos:
      - "linux"
      - "darwin"
    goarch:
      - "amd64"
      - "arm64"
    ldflags:
      - -s
      - -w
      - -X "main.version={{.Version}}"
      - -X "main.commit={{.Commit}}"
      - -X "main.date={{.Date}}"
archives:
  - name_template: "gh-web-auth_{{.Version}}_{{.Os}}_{{.Arch}}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{.Tag}}-next"
changelog:
  disable: true
nfpms:
  -
    id: "gh-web-auth"
    package_name: "gh-web-auth"
    homepage: "https://github.com/Eun/gh-web-auth"
    maintainer: "Tobias Salzmann <tobias@salzmann.berlin>"
    description: "Web UI for GitHub CLI authentication via OAuth device flow"
    license: "MIT"
    formats:
      - "deb"
    epoch: 1
dockers:
  -
    id: "gh-web-auth-amd64"
    goos: "linux"
    goarch: "amd64"
    ids:
      - "gh-web-auth"
    image_templates:
      - "ghcr.io/eun/gh-web-auth:{{.Tag}}-amd64"
    skip_push: false
    dockerfile: ".github/Dockerfile"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--build-arg=BINARY=gh-web-auth"
      - "--platform=linux/amd64"
  -
    id: "gh-web-auth-arm64"
    goos: "linux"
    goarch: "arm64"
    ids:
      - "gh-web-auth"
    image_templates:
      - "ghcr.io/eun/gh-web-auth:{{.Tag}}-arm64"
    skip_push: false
    dockerfile: ".github/Dockerfile"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--build-arg=BINARY=gh-web-auth"
      - "--platform=linux/arm64"
docker_manifests:
  -
    name_template: "ghcr.io/eun/gh-web-auth:{{.Tag}}"
    image_templates:
      - "ghcr.io/eun/gh-web-auth:{{.Tag}}-amd64"
      - "ghcr.io/eun/gh-web-auth:{{.Tag}}-arm64"
  -
    name_template: "ghcr.io/eun/gh-web-auth:{{.Major}}"
    image_templates:
      - "ghcr.io/eun/gh-web-auth:{{.Tag}}-amd64"
      - "ghcr.io/eun/gh-web-auth:{{.Tag}}-arm64"
  -
    name_template: "ghcr.io/eun/gh-web-auth:{{.Major}}.{{.Minor}}"
    image_templates:
      - "ghcr.io/eun/gh-web-auth:{{.Tag}}-amd64"
      - "ghcr.io/eun/gh-web-auth:{{.Tag}}-arm64"
  -
    name_template: "ghcr.io/eun/gh-web-auth:latest"
    image_templates:
      - "ghcr.io/eun/gh-web-auth:{{.Tag}}-amd64"
      - "ghcr.io/eun/gh-web-auth:{{.Tag}}-arm64"
